id: 'fd238fab-5947-410e-9bfc-08dd9c3f3d0a'
name: 'C4-X-SF-DV-Email-StageFile'
description: ' Stage File project containing the person email data from a Parquetfile'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Snowflake.File'
  version: '1.9.3'
sourceSystems:
  - id: '4950e25e-3351-4e1a-87b8-29c750b841e6'
    name: 'paequetConn'
    description: ''
    activeDiscovery: 'ecdc5961-36fb-432a-9337-ab521a1552af'
    sourceSystemTypeId: '874926da-0cf2-450f-b761-a0c9a85646f6'
